### ISSUE TITLE
Binpack option crashes tool

### ISSUE THREAD

**Issue by ACosmicCake** [fairy-stockfish/variant-nnue-tools#14]
The default datageneration binpack function crashes the uci protocol for me. i have to switch to generation of /bin file instead. 

Also conversion from .bin to bin.pack also crashes. 

and validate training data on .bin files also crash :( 

Please help :( 

There is what i use for trainning: 
uci
setoption name Use NNUE value false
setoption name Threads value 18
setoption name Hash value 5120
setoption name UCI_Variant value siege
isready
generate_training_data depth 3 count 1000000000 random_multi_pv 4 random_multi_pv_diff 100 random_move_count 8 random_move_max_ply 20 write_min_ply 5 eval_limit 10000 set_recommended_uci_options data_format  binpack output_file_name your_variant.binpack
quit

(This crashes because it uses binpack filetype, unless i switch to bin)

**Comment by ianfab** [comment]
Binpack is a highly compressed format that requires knowledge about the rules of the game in order to achieve the compression. In the generic framework here this is extremely hard to do, which is why it is not supported, and very likely also won't be in the future.

This is to some extent documented in the wiki, so I would refer to that, but I do understand that this should be documented better or ideally the code should just not allow for it. The reason why it currently is in this state is that it used to be private code that I then decided to publish it anyway, so it looks a bit more hacky than it should.
