### ISSUE TITLE
训练崩溃

### ISSUE THREAD

**Issue by shuangqiao999** [fairy-stockfish/variant-nnue-tools#4]
你好 我用fairy-stockfish-tools-largeboard_x86-64-modern.exe 训练几分钟就崩溃了 命令行输入generate_training_data depth 10 count 1000000 keep_draws 1 eval_limit 32000  win10系统 线程设置为4 哈希值设置为512mb 试了几次都是崩溃 请问这是怎么回事？

**Comment by ianfab** [comment]
Is `generate_training_data depth 10 count 1000000 keep_draws 1 eval_limit 32000` the complete command you used? If so that won't work, because at least the `data_format bin` is missing, also see the example at https://github.com/ianfab/variant-nnue-pytorch/wiki/Training-data-generation#example. Otherwise please provide the entire sequence of commands you use.

**Comment by shuangqiao999** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by shuangqiao999** [comment]
Hello  setting name using NNUE values "true" and "pure"? Does using "true" allow both classical and NNUE calculations? Are hybrid calculations better than pure NUE calculations?
